#!/bin/sh

libtool --mode=execute "valgrind --tool=massif --alloc-fn=g_slice_new --alloc-fn=g_slice_alloc --alloc-fn=g_slice_alloc0 \
			--alloc-fn=g_malloc --alloc-fn=g_realloc --alloc-fn=g_try_malloc --alloc-fn=g_malloc0 \
			--alloc-fn=g_object_new --alloc-fn=g_object_new_valist --alloc-fn=g_object_newv --alloc-fn=g_type_init
			--alloc-fn=profiler_calloc --alloc-fn=profiler_malloc --alloc-fn=profiler_realloc" ./general
